group: deprecated-2017Q4
language: python
before_install:
- git config --global user.name "uldaman"
- git config --global user.email "zhuec@hotmail.com"
- sed -i "s#https://github.com#https://${GHTOKEN}@github.com#g" .git/config
- sed -i "s#git@github.com:#https://${GHTOKEN}@github.com/#g" .git/config
install:
- pip install bulrush==0.3.2
- pip install invoke
- pip install ghp-import
- pip install pelican
- pip install 'markdown<3'
script:
- invoke gh-pages
branches:
  only:
  - markdown
